config/routes.rb
Cancan::Application.routes.draw do
  devise_for :users

  get "sessions/new"
 
  resources :homes
  resources :articles
  

  devise_scope :user do
    root to: 'devise/sessions#new'
  end

  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    # user ||= User.new # guest user (not logged in)
   
        if user.role? :admin
            can :manage, :all
        else
            can :read, :all
        end
  
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :description, :name
end

app/models/role.rb
class Role < ActiveRecord::Base
  attr_accessible :name
  has_many :user_roles
  has_many :users, through: :user_roles
  accepts_nested_attributes_for :user_roles
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :om	niauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

 # Setup accessible (or protected) attributes for your model

 attr_accessible :email, :password, :password_confirmation, :remember_me
 has_many :user_roles
 has_many :roles, through: :user_roles	
 #accepts_nested_attributes_for :user_roles
 
	def role?(role)
    return !!self.roles.find_by_name(role.to_s)
end
  validates_uniqueness_of :email
end

app/models/user_role.rb
class UserRole < ActiveRecord::Base
  attr_accessible :role_id, :user_id
  belongs_to :role
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to homes_url, :alert => exception.message
  end

  def after_sign_in_path_for(resource)
    stored_location_for(resource) || homes_path
  end

  def after_sign_out_path_for(resource_name)
	  root_path
	end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_filter :authenticate_user!
	load_and_authorize_resource
	
	def new
		@article = Article.new
	end

	def create
		logger.debug "params = #{params.to_s}"
		@article = Article.new(params[:article])
    if @article.save
      redirect_to @article
    else
      render "new"
    end
	end

	def show
		@article = Article.find(params[:id])
	end

	def edit
		 @article = Article.find(params[:id])
	end

  def update
    @article = Article.find(params[:id])
    if @article.update_attributes(params[:article])
  		redirect_to @article, notice: 'Article was successfully updated.'
    else
     render action: "edit" 
    end
  end

	def destroy
		@article = Article.find(params[:id])
    @article.destroy
    redirect_to homes_url
	end 
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	before_filter :authenticate_user!
	def index
		@articles = Article.all
		@users = User.all
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new

	end

	def create
	  user = User.find_by_email(params[:email])
	  if user && user.valid_password?(params[:password])
	  						
	  	session[:user_id] = user.id
	    redirect_to :homes
	  else
	    flash.now.alert = "Email or password is invalid."
	    render "new"
	  end	
	end

	def destroy
  session[:user_id] = nil
  redirect_to root_url, notice: "Logged out!"
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      redirect_to homes_url
    else
      render "new"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/signups_helper.rb
module SignupsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/edit.html.erb
<% if current_user %>
    Logged in as <%= current_user.email %>.
<% end %>
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div>
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>
</br>
</br>
</br>
<%= link_to "Log Out", session_path("current"), method: "delete" %>

app/views/articles/new.html.erb
<h1>Create Article</h1>

<%= form_for @article, :url => articles_path do |f| %>
  <div>
          <%= label_tag :name %><br />
          <%= f.text_field :name %>
  </div>
  <div>
          <%= label_tag :description %><br />
          <%= f.text_area :description %>
  </div>
  <div><%= submit_tag "create" %></div>
<% end %>
</br>
</br>
<%= link_to "Logout",destroy_user_session_path, :method => :delete %>

app/views/articles/show.html.erb
<% if can? :update, @article %>
	<%= link_to "edit", edit_article_url(@article.id) %>
<% end %>

<% if can? :destroy, @article %>
	<%= link_to 'Destroy', article_url(@article.id), method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>
<%= link_to "back", homes_url %>
<h1>
	<%= @article.name %>
</h1>
<div>
	<%= @article.description %>
</div>

app/views/home/index.html.erb
<%= form_for @user do |f| %>
  <div>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div><%= f.submit "Log in" %></div>
   <%= link_to "Sign Up", new_user_path %>
<% end %>

app/views/homes/index.html.erb
<div id="user_header">
  <% if current_user %>
    Logged in as <%= current_user.email %>.
  <% else %>
    <%= link_to "Sign Up", new_user_path %> or
    <%= link_to "Log In", new_session_path %>
   <% end %>
</div>

<h1>Articles</h1>
<%= link_to "Create New Article", new_article_url %>

<% @articles.each do |article| %>
  <div>
  	<%= link_to article.name, article_url(article.id) %>
  </div>
<% end %>
<% @users.each do |user| %>
  <div>
  	<%= user.email %>
  </div>
<% end %>
<br>
</br>
</br>
<%= link_to "Logout",destroy_user_session_path, :method => :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cancan</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<p><%= notice %></p>
  <p><%= alert %></p>
<%= yield %>
</body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user, :url => users_url  do |f| %>
 

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Sign Up" %></div>
<% end %>

<%= link_to "cancel", root_url %>